# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: models.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 28, 3, "", "models.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cmodels.proto\x12\x0cproto_chango"5\n\x04Node\x12\n\n\x02id\x18\x01 \x02(\t\x12!\n\x05nodes\x18\x02 \x03(\x0b\x32\x12.proto_chango.Node"\x19\n\x08\x44\x61teTime\x12\r\n\x05value\x18\x01 \x02(\t"x\n\x06Object\x12 \n\x04node\x18\x03 \x02(\x0b\x32\x12.proto_chango.Node\x12\x0c\n\x04name\x18\x04 \x02(\t\x12\x12\n\ncreated_at\x18\x05 \x02(\t\x12*\n\nupdated_at\x18\x06 \x02(\x0b\x32\x16.proto_chango.DateTime'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "models_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_NODE"]._serialized_start = 30
    _globals["_NODE"]._serialized_end = 83
    _globals["_DATETIME"]._serialized_start = 85
    _globals["_DATETIME"]._serialized_end = 110
    _globals["_OBJECT"]._serialized_start = 112
    _globals["_OBJECT"]._serialized_end = 232
# @@protoc_insertion_point(module_scope)
